version: '3.8'
name: mariadb-compose
services:
  mariadb:
    container_name: "mariadb-server"
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: MyStrongPassword2019
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - "3306:3306"
    user: root
    network_mode: bridge
    restart: unless-stopped
    volumes:
      - mariadbvol:/var/lib/mysql
volumes:
  mariadbvol:
    external: true